import https from 'https';
import fs from 'fs';
import { app } from 'electron';
import { Agent as UndiciAgent, fetch as undiciFetch } from 'undici';

/**
 * In packaged (production) mode, agents default to strict TLS verification.
 * configureTrustAnchor() must be called with the service cert before making
 * requests — calls will fail until then, which is the correct safety behavior.
 *
 * In dev mode (app.isPackaged === false), agents start with rejectUnauthorized:false
 * so the app works before a self-signed cert is generated.
 */
const isDevMode = !app.isPackaged;
let localAgent = new https.Agent({ rejectUnauthorized: !isDevMode });
let localUndiciAgent = new UndiciAgent({ connect: { rejectUnauthorized: !isDevMode } });

/**
 * Switch the HTTPS agents to verify the service certificate against a pinned CA
 * (the self-signed cert generated by productionConfig on first run).
 * Called from serviceManager after the cert path is known.
 * In packaged mode this MUST be called before making requests (agents default
 * to strict verification). No-op if certPath is empty or file does not exist.
 */
export function configureTrustAnchor(certPath: string): void {
  if (!certPath || !fs.existsSync(certPath)) return;
  const ca = fs.readFileSync(certPath);
  localAgent = new https.Agent({ ca, rejectUnauthorized: true });
  localUndiciAgent = new UndiciAgent({ connect: { ca, rejectUnauthorized: true } });
}

interface LocalResponse {
  ok: boolean;
  status: number;
  json: <T = unknown>() => Promise<T>;
}

/**
 * Drop-in replacement for fetch() in the Electron main process when calling
 * the local service over HTTPS with a self-signed certificate.
 * In packaged mode the agent requires CA-pinning via configureTrustAnchor().
 * In dev mode it accepts any localhost self-signed cert.
 */
export async function localFetch(
  url: string,
  init?: {
    method?: string;
    headers?: Record<string, string>;
    body?: string;
  },
): Promise<LocalResponse> {
  return new Promise((resolve, reject) => {
    const parsed = new URL(url);
    const req = https.request(
      {
        hostname: parsed.hostname,
        port: parseInt(parsed.port || '443', 10),
        path: parsed.pathname + parsed.search,
        method: init?.method ?? 'GET',
        headers: {
          'Content-Type': 'application/json',
          ...init?.headers,
        },
        agent: localAgent,
      },
      (res) => {
        const chunks: Buffer[] = [];
        res.on('data', (c: Buffer) => chunks.push(c));
        res.on('end', () => {
          const raw = Buffer.concat(chunks).toString('utf8');
          resolve({
            ok: (res.statusCode ?? 0) >= 200 && (res.statusCode ?? 0) < 300,
            status: res.statusCode ?? 0,
            json: <T>() => {
              try { return Promise.resolve(JSON.parse(raw) as T); }
              catch { return Promise.reject(new Error('Invalid JSON in service response')); }
            },
          });
        });
      },
    );
    req.on('error', reject);
    if (init?.body) req.write(init.body);
    req.end();
  });
}

/**
 * localFetch variant for FormData/multipart requests (e.g. file uploads).
 * Uses undici's fetch with the same CA-pinned (or dev-mode relaxed) agent.
 */
export function localFetchForm(url: string, init: RequestInit): Promise<Response> {
  return undiciFetch(url, {
    ...(init as Record<string, unknown>),
    dispatcher: localUndiciAgent,
  }) as unknown as Promise<Response>;
}
